todo/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signupuser, name = "signupuser"),
    path('currenttodos/', views.currenttodos, name = "currenttodos"),
    path('logout/',views.logoutuser, name = "logoutuser"),
    path('', views.home, name = "home"),
    path('login/', views.loginuser, name = "loginuser"),
    path('create_todos/', views.create_todos, name = "create_todos"),
    path('todo/<int:view_todo>', views.view_todo, name = "view_todo"),
    path('todo/<int:complete_todo>/completed', views.complete, name = "complete"),
    path('todo/<int:deleted_todo>/deleted', views.delete, name = "delete"),
    path('completed/', views.completedtodos, name='completedtodos'),

   
    
]

todowoo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('signup/', include('signup.urls')),
    path('', include('todo.urls')),

]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length = 100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    date_on_completed = models.DateTimeField(blank =True, null = True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import Todo

class create_todoform(ModelForm):
    """Form definition for MODELNAME."""

    class Meta:
        """Meta definition for MODELNAMEform."""

        model = Todo
        fields = ('title', 'memo', 'important')

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import create_todoform
from .models import Todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):

    return render(request, "home.html")




def signupuser(request):

    if request.method == "GET":
        return render(request, "signup.html", {'form': UserCreationForm()})

    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request,user)

                return redirect('currenttodos')



            except IntegrityError:
                return render(request, "signup.html", {'form': UserCreationForm(), 'error': 'This username already exists'})


            
            

        else:
            return render(request, "signup.html", {'form': UserCreationForm(), 'error': 'Password did not match'})

@login_required(login_url='/login/')
def currenttodos(request):
    todos = Todo.objects.filter(user = request.user, date_on_completed__isnull = True)
    return render(request, 'currenttodos.html', {'todos' : todos})

@login_required(login_url='/login/')
def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')    



def loginuser(request):
    if request.method == "GET":
        return render(request, "login.html", {'form': AuthenticationForm()})

    else:
        user = authenticate(username = request.POST['username'], password = request.POST['password'])

        if user is None:
            return render(request, "login.html", {'form': AuthenticationForm(), 'error': 'username or password is incorrect' })

        else:
            login(request,user)
            return redirect('currenttodos')


@login_required(login_url='/login/')
def create_todos(request):
    if request.method == "GET":
        return render(request, "create_todos.html", {'form': create_todoform()})

    else:
        try:
            form = create_todoform(request.POST)
            new_obj = form.save(commit=False)
            new_obj.user = request.user
            new_obj.save()
            return redirect('currenttodos')

        except ValueError:
            return render(request, "create_todos.html", {'form': create_todoform(), 'error' : "Maximum length exceeded"})

@login_required(login_url='/login/')
def view_todo(request, view_todo):
    todo = get_object_or_404(Todo, pk=view_todo, user = request.user)
    if request.method == "GET":
        form = create_todoform(instance = todo)
        return render(request, "view.todo.html", {'todo': todo, 'form': form})

    else:
        try:
            form = create_todoform(request.POST, instance=todo)
            form.save()
            return redirect('currenttodos')

        except ValueError:
            return render(request, "view.todo.html", {'todo': todo, 'form': form, 'error': "Bad Input"})

@login_required(login_url='/login/')
def complete(request, complete_todo):
        todo = get_object_or_404(Todo, pk=complete_todo, user = request.user)
        if request.method == "POST":
            todo.date_on_completed = timezone.now()
            todo.save()
            return redirect('currenttodos')

@login_required(login_url='/login/')
def delete(request, deleted_todo):
        todo = get_object_or_404(Todo, pk=deleted_todo, user = request.user)
        if request.method == "POST":
            todo.delete()
            return redirect('currenttodos')


@login_required(login_url='/login/')
def completedtodos(request):
    todos = Todo.objects.filter(user=request.user, date_on_completed__isnull=False).order_by('-date_on_completed')
    return render(request, 'completedtodos.html', {'todos' : todos})


    
        

        

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todo/logo.css' %}">
  </head>
  <body>

    <nav class="navbar py-3 navbar-light navbar-expand-sm bg-warning">
      <a class="navbar-brand" href="{% url 'home' %}"> <img src="https://www.psdgraphics.com/wp-content/uploads/2011/10/right.jpg" width="50" height="50" alt=""> </a>
      <div class="collapse navbar-collapse" id="navbarLinks">

       


        {% if user.is_authenticated %}

        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item active"><a href="{% url 'completedtodos' %}" class="nav-link">Completed</a></li>

        </ul>

        {% endif %}

        <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated %}
          
          <li class="nav-item active"><a href="" class="nav-link">{{user.username}}</a></li>
          
          <li class="nav-item">
            <form id="myform" method="post" action="{% url 'logoutuser' %}">{% csrf_token %}</form>
            <a class="nav-link logout" onclick="document.getElementById('myform').submit();">logout</a>
          </li>
        
     

         {% else %}
          
          <li class="nav-item"><a href="{% url 'loginuser' %}" class="nav-link">Sign in</a></li>
          <li class="nav-item"><a href="{% url 'signupuser' %}" class="nav-link">Sign up</a></li>

          {% endif %}

        </ul>


        </div>

    </nav>




    <!-- {% if user.is_authenticated %}

    <p>logged in as {{user.username}}</p>

   
    <form action="{% url 'logoutuser' %}" method="POST">
        {% csrf_token %} 
        <input type="submit" value="logout">
    </form>

    {% else %}
    <a href="{% url 'loginuser' %}">Sign in</a>
    <a href="{% url 'signupuser' %}">Sign up</a>

    {% endif %} -->

 
    
      {% block blockname %}
        
      {% endblock blockname %}
      
    
 
        
        






      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/completedtodos.html
{% extends 'base.html' %}


{% block blockname %}
<section id="completedtodos" class="py-3">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1>Completed Todos</h1>
             
            </div>
        </div>

        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                {% if todos %}
                <ul class="list-group">
                    {% for todo in todos %}
                    <a href="{% url 'view_todo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"> <b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %} </a>

                    {% endfor %}
                </ul>

                {% else %}
                
                <h2 >Looks like you don't have any todos! Nice work.</h2>

                <div class="text-center">

                <a href="{% url 'create_todos' %}" class="btn btn-primary mt-3">Create Todo</a>

                </div>

                {% endif %}
            </div>
        </div>

</section>

{% endblock blockname %}

templates/create_todos.html
{% extends 'base.html' %}

{% block blockname %} 

      <!-- <h2>{{error}}</h2>
    <form action="" method="POST">
        {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="create">

    </form> -->

    <section id="create-todos">
        <div class="container mt-5">
            <div class="row justify-content-center mt-5">
                <div class="col-md-8 mt-4">
                    {% if error %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                    {% endif %}
    
                    <h1>New Todo</h1>
    
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group mt-3">
                        <label for="title">Title</label>
                        <input type="text" name="title" class="form-control" id="">
                    </div>
    
                    <div class="form-group">
                        <label for="id_memo">Memo</label>
                        <textarea style="resize: none;" name="memo" id="id_memo" cols="30" rows="5" class="form-control"></textarea>
                    </div>

                    <div class="form-group form-check">
                        <input class="form-check-input" type="checkbox" name="important" id="id_important">
                        <label class="form-check-label" for="id_important">Important:</label>
                    </div>
       
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
        
                </div>
            </div>
        </div>
    </section>
    

{% endblock blockname %}
    

templates/currenttodos.html
{% extends 'base.html' %}


{% block blockname %}

<!-- <h2>Current Todos</h2>

<ul>
    {% for todo in todos %}
    <li>
        <a href="{% url 'view_todo' todo.id %}">{% if todo.important %}<strong>{% endif %} {{todo.title}} {% if todo.important %}</strong>{% endif %}
        {% if todo.memo%} - {{todo.memo}} {% endif %}
        </a>
    </li>    
    {% endfor %}
</ul> -->

<section id="completedtodos" class="py-3">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% if todos %}
                <h1>{{ todos.count }} Current Todo{{ todos.count|pluralize }}</h1>
                {% else %}
                <h1>Current Todos</h1>
                {% endif %}
            </div>
        </div>

        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                {% if todos %}
                <ul class="list-group">
                    {% for todo in todos %}
                    <a href="{% url 'view_todo' todo.id %}" class="list-group-item list-group-item-action{% if todo.important %} list-group-item-danger{% endif %}"> <b>{{ todo.title }}</b>{% if todo.memo %} - {{ todo.memo|truncatechars:30 }}{% endif %} </a>

                    {% endfor %}
                </ul>

                {% else %}
                
                <h2 >Looks like you don't have any todos! Nice work.</h2>

                <div class="text-center">

                <a href="{% url 'create_todos' %}" class="btn btn-primary mt-3">Create Todo</a>

                </div>

                {% endif %}
            </div>
        </div>
      
         
        

    </div>
</section>
    
{% endblock blockname %}
    

templates/home.html
{% extends 'base.html' %}


{% block blockname %}


<!-- <section>
  <div class="container mt-5">

    <div class="row justify-content-center mt-5">

        <div class="col-md-8 text-center mt-5">

            

            <h1 class="mt-5 pt-5">Simply Your Todos. Woo!</h1>
            <p>Life is fun. But life is also busy. There's a million different things you could be doing. But what matters is <u>what</u> you do. We created <b><i>Todo Woo</i></b> to help you make sense of all of your opportunities and live that life that matters most to you. Your new organized life awaits.</p>
           
            <form action="#" method="get">
                {% csrf_token %}
                <a class="btn btn-primary" href="{% url 'signupuser' %}">Start</a>
            </form>

        </div>

    
        
    </div>

  </div>

</section> -->
      

<header id="header" class="bg-light">
  <div class="container">
    <div class="row height align-items-center justify-content-center">
      <div class="col-md-8 text-center">
        <h1>Simply Your Todos. Woo!</h1>
        <p class="text-dark lead">Life is fun. But life is also busy. There's a million different things you could be doing. But what matters is <u>what</u> you do. We created <b><i>Todo Woo</i></b> to help you make sense of all of your opportunities and live that life that matters most to you. Your new organized life awaits.</p>
        {% if user.is_authenticated %}
        <a href="{% url 'currenttodos' %}" class="btn btn-primary mt-3">Let's Start</a>

        {% else %}
        <a href="{% url 'signupuser' %}" class="btn btn-danger">Start</a>


        {% endif %}
    </div>
  </div>
</header>



    

        
    


      

  

    

 


    
{% endblock blockname %}
    

templates/login.html
{% extends 'base.html' %}

{% block blockname %} 

    <!-- <h2>Signup</h2>
    <h2>{{error}}</h2>
    <form action="" method="POST">
        {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Log in">

    </form> -->

    <section id="login" class="py-3">
        <div class="container mt-5">
            <div class="row justify-content-center mt-5">
                <div class="col-md-8 mt-5">
                    {% if error %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                    {% endif %}
    
                    <h1>Log in</h1>
    
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group mt-3">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control" id="">
                    </div>
    
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" class="form-control" id="">
                    </div>
       
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                </form>
    
    
                </div>
            </div>
        </div>
    </section>
    

{% endblock blockname %}
    

templates/signup.html
{% extends 'base.html' %}

{% block blockname %}

    <!-- <h2>Signup</h2>
    <h2>{{error}}</h2>
    <form action="" method="POST">
        {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="Signup">

    </form> -->
    
<section id="signup" class="py-3 bg-light">
    <div class="container mt-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8 mt-4">
                {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
                {% endif %}

                <h1>Sign Up!</h1>

            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group mt-3">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="">
                    <small class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>

                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="">
                </div>

                <div class="form-group">
                    <label for="password2">Confirm Password :</label>
                    <input type="password" name="password2" class="form-control" id="">
                </div>

                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>

            <strong><p class="text-center mt-4">Do you already have an account <a href="{% url 'loginuser' %}">click here !</a></p></strong>

            </div>
        </div>
    </div>
</section>
              

     



{% endblock blockname %}
    

templates/view.todo.html
{% extends 'base.html' %}


{% block blockname %}
<!-- {{error}}
{{todo.title}}

<form action="" method="POST">
    {% csrf_token %}

{{form.as_p}}

<input type="submit" value="Save">

</form>

<form action="{% url 'complete' todo.id %}" method="POST">
    {% csrf_token %}


<input type="submit" value="Complete">

</form>

<form action="{% url 'delete' todo.id %}" method="POST">
    {% csrf_token %}


<input type="submit" value="Delete">

</form> -->


<section id="view_todo">
    <div class="container mt-5">
        <div class="row justify-content-center mt-5">
            <div class="col-md-8 mt-4">
                {% if error %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
                {% endif %}

                <h1>Todo</h1>

            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group mt-3">
                    <label for="id_title">Title</label>
                    <input type="text" name="title" class="form-control" id="id_title" value="{{todo.title}}">
                </div>

                <div class="form-group">
                    <label for="id_memo">Memo</label>
                    <textarea style="resize: none;" name="memo" id="id_memo" cols="30" rows="5" class="form-control">{{todo.memo}}</textarea>
                </div>

                <div class="form-group form-check">
                    <input class="form-check-input" type="checkbox" name="important" id="id_important" {% if todo.important %}checked{% endif %}>
                    <label class="form-check-label" for="id_important">Important:</label>
                </div>
   
                <button type="submit" class="btn btn-primary m-2">Save</button>

                
                {% if todo.datecompleted is None %}
                  <button class="btn btn-success m-2" type="submit" onclick="$('#complete').submit(); return false;" title="My link title">Complete</a> 
         
                

                {% endif %}

                <button class="btn btn-danger m-2" type="submit" onclick="$('#delete').submit(); return false;" title="My link title">Delete</a> 
         
  
                    
            </form>
    
            </div>
        </div>
    </div>
</section>

<form id="complete" action="{% url 'complete' todo.id %}" method="post" style="display: none">
    {% csrf_token %}
    <button type="hidden" name="myParameterName" value="myParameterValue">Complete</button>
  </form>

  <form id="delete" action="{% url 'delete' todo.id %}" method="post" style="display: none">
    {% csrf_token %}
    <button type="hidden" name="myParameterName" value="myParameterValue">Complete</button>
  </form>





    
{% endblock blockname %}